[project]
name = "codspeed-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asbestos>=1.6.1",
    "pytest>=8.3.5",
    "pytest-codspeed>=3.2.0",
]
